export const SET_CURRENCY = 'SERVER/SET_CURRENCY';
export const SET_CURRENCY_REFILL = 'SERVER/SET_CURRENCY_REFILL';
export const SET_STATISTIC = 'SERVER/SET_STATISTIC';

export const CHANGE_CURRENCY = 'SERVER/CHANGE_CURRENCY';
export const CHANGE_CAPACITY = 'SERVER/CHANGE_CAPACITY';
export const CHANGE_INVENTORY = 'SERVER/CHANGE_INVENTORY';
export const CHANGE_STATISTIC = 'SERVER/CHANGE_STATISTIC';

export const CREATE_SUBSCRIPTION = 'CLIENT/CREATE_SUBSCRIPTION';

export const REQUEST_STATISTIC = 'CLIENT/REQUEST_STATISTIC';
export const REQUEST_STATISTICS = 'CLIENT/REQUEST_STATISTICS';
export const STATISTIC = 'SERVER/STATISTIC';
export const REQUEST_CATALOG = 'CLIENT/REQUEST_CATALOG';
export const CATALOG = 'SERVER/CATALOG';
export const REQUEST_INVENTORY = 'CLIENT/REQUEST_INVENTORY';
export const INVENTORY = 'SERVER/INVENTORY';
export const ADD_TO_INVENTORY = 'SERVER/ADD_TO_INVENTORY';
export const REQUEST_LEADERBOARD = 'CLIENT/REQUEST_LEADERBOARD';
export const LEADERBOARD = 'SERVER/LEADERBOARD';
export const LEADERBOARD_RANK = 'SERVER/LEADERBOARD_RANK';

