export const SET_CURRENCY = 'SERVER/SET_CURRENCY';
export const SET_CURRENCY_REFILL = 'SERVER/SET_CURRENCY_REFILL';
export const SET_STATISTIC = 'SERVER/SET_STATISTIC';

export const CHANGE_CURRENCY = 'SERVER/CHANGE_CURRENCY';
export const CHANGE_CAPACITY = 'SERVER/CHANGE_CAPACITY';
export const CHANGE_INVENTORY = 'SERVER/CHANGE_INVENTORY';
export const CHANGE_STATISTIC = 'SERVER/CHANGE_STATISTIC';
export const CHANGE_STATISTIC_TO = 'SERVER/CHANGE_STATISTIC_TO';

export const CREATE_SUBSCRIPTION = 'CLIENT/CREATE_SUBSCRIPTION';

export const REQUEST_STATISTIC = 'CLIENT/REQUEST_STATISTIC';
export const REQUEST_STATISTICS = 'CLIENT/REQUEST_STATISTICS';
export const STATISTIC = 'SERVER/STATISTIC';

export const REQUEST_CATALOG = 'CLIENT/REQUEST_CATALOG';
export const CATALOG = 'SERVER/CATALOG';

export const REQUEST_INVENTORY = 'CLIENT/REQUEST_INVENTORY';
export const INVENTORY = 'SERVER/INVENTORY';
export const ADD_TO_INVENTORY = 'SERVER/ADD_TO_INVENTORY';

export const REQUEST_LEADERBOARD = 'CLIENT/REQUEST_LEADERBOARD';
export const LEADERBOARD = 'SERVER/LEADERBOARD';
export const LEADERBOARD_RANK = 'SERVER/LEADERBOARD_RANK';

export const SEND_NOTIFICATION = 'SERVER/SEND_NOTIFICATION';
export const PUSH_NOTIFICATION = 'SERVER/PUSH_NOTIFICATION';
export const REQUEST_NOTIFICATIONS = 'CLIENT/REQUEST_NOTIFICATIONS';
export const NOTIFICATIONS = 'SERVER/NOTIFICATIONS';
export const READ_NOTIFICATIONS = 'CLIENT/READ_NOTIFICATIONS';
export const READ_NOTIFICATION = 'CLIENT/READ_NOTIFICATION';
export const STATISTIC_CHANGE_NOTIFICATION = 'SERVER/STATISTIC_CHANGE_NOTIFICATION';
export const REQUEST_SEND_NOTIFICATION = 'CLIENT/REQUEST_SEND_NOTIFICATION';

export const SCHEDULE_ACTION = 'SERVER/SCHEDULE_ACTION';

export const ADD_SESSION_TO_GROUP = 'SERVER/ADD_SESSION_TO_GROUP';
export const REMOVE_SESSION_FROM_GROUP = 'SERVER/REMOVE_SESSION_FROM_GROUP';
export const SET_SESSION_METADATA = 'SERVER/SET_SESSION_METADATA';
export const UNSET_SESSION_METADATA = 'SERVER/UNSET_SESSION_METADATA';
export const SESSION_GROUP_UPDATE = 'SERVER/SESSION_GROUP_UPDATE';
export const SESSION_METADATA_UPDATE = 'SERVER/SESSION_METADATA_UPDATE';
export const ACCOUNT_GROUP_UPDATE = 'SERVER/USER_GROUP_UPDATE';

